{{- if .Values.superstreamAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "superstream.serviceAccountName" . }}
  labels:
    {{- include "superstream.labels" . | nindent 4 }}
  {{- with .Values.superstreamAgent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
