{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datadog.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datadog.labels" . | nindent 4 }}
data:
  kubelet.yaml: |
    init_config: {}
    instances:
      - cadvisor_port: 0
        metrics_endpoint: ""
  
  datadog-agent-logs.yaml: |
    logs:
      - type: file
        path: /var/log/datadog/agent.log
        service: datadog-agent
        source: datadog-agent
{{- end }}

